
console.log('01) ', '1' == 1)       // true  -> sao iguai... compara o valor e ignora o tipo...
console.log('01) ', '1' === 1)      // false -> nao sao iguais... pois compara valor e tipo...
console.log('03) ', '3' != 3)       // false -> nao sao diferentes, sao iguais... compara somente o valor...
console.log('04) ', '3' !== 3)      // true  -> sao diferentes... pois o tipo e diferente... 

console.log('05) ', 3 < 2)   // false
console.log('06) ', 3 > 2)   // true
console.log('07) ', 3 <= 2)  // false
console.log('08) ', 3 >= 2)  // true

const d1 = new Date(0)
const d2 = new Date(0)
console.log('09) ', d1 === d2)  // false -> comparacao de referencia: tanto faz comparar com '===' ou '=='...
console.log('10) ', d1 == d2)   // false -> comparacao de referencia: tanto faz comparar com '===' ou '=='...
console.log('11) ', d1.getTime() === d2.getTime())   // true -> comparacao de valor...

console.log('12) ', undefined == null)   // true -> comparacao de valor...
console.log('13) ', undefined === null)   // false -> comparacao de tipo...


